### PR TITLE
Nix support & automated update

### PR DESCRIPTION
**Pull request by Austreelis**
This PR supersedes #96.

It updates it by:
- Using `buildGoModule118`
- Installing shell completions along
- `vendorSha256` is (and should keep being) up-to-date with `master`

It also adds:
- Nightly update of `flake.lock`
- ~~Nightly~~ Automatic updates of the nix package's `vendorSha256`
- A formatter so that running `nix fmt` formats all nix code.

<details><summary>Outdated</summary>

There's still a few questions remaining:
- Nix needs to know which systems are supported. I've included all systems the github workflow currently builds artifacts for, except windows (see `supportedSystems` in `flake.nix`). I suppose that's okay ?
- I've put all nix files in the `nix/` directory. That comes with a slight ergonomic disadvantage for people that want to use packwiz' flake (having to add `?dir=nix` at the end of the flake url given to a nix command, i.e. `github:packwiz/packwiz?dir=nix` instead of the typical `github:packwiz/packwiz`). By convention, `flake.nix` should be in the root directory, and I think it should go there, but keeping it under `nix/` is a possibility I wanted to leave open. I could put the files in the root directory like the original PR though, if that's not an issue.
- The package's version are formatted like `nightly-YYYY-MM-dd`, and it's currently not possible to change that other than manually editing `flake.nix` & friends. Would it be desirable ?

</details>

### CODE REVIEW

**Comment by TheOPtimal** [comment]
Why not just use flake-compat instead of having all the shenanigans in the nix files?

**Comment by Austreelis** [comment]
I think having a derivation inlined in flake.nix makes it less readable. That's also strictly the same for the flake user, unless I'm missing some details, and I'm not a fan of fetching one more tarball when it doesn't change anything.

That said that's an vasy change if @comp500 disagrees.

**Comment by Austreelis** [comment]
> This shouldn't be done, because by convention, the flake is always in the root of the repository.

The PR isn't really clear about the fact it's a convention, indeed.

> this is easily corrected by moving flake.nix/flake.lock to the root,

That's why I considered it okay to just push that first so packwiz can choose which solution fits it best.

I think it's best to put it in the root, but when I wrote the PR I couldn't write that clearly enough apparently (I was very tired).

**Comment by comp500** [comment]
> Nix needs to know which systems are supported.

packwiz should technically support any system supported by Go (I don't think it uses any `cgo`) so there are [quite a number of supported systems](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63). Due to https://github.com/packwiz/packwiz/issues/107 I don't provide 32-bit builds currently, but once that's fixed they should be usable (though I probably won't add them back to GH actions since they mostly just confuse people).

> I could put the files in the root directory like the original PR though, if that's not an issue.

Having just `flake.nix` and `flake.lock` in the root directory like Infinidoge suggested sounds good to me, should keep things a bit cleaner while still supporting the convention.

> The package's version are formatted like nightly-YYYY-MM-dd, and it's currently not possible to change that other than manually editing flake.nix & friends. Would it be desirable ?

I don't particularly mind since I presume it's not a version number pushed to any public repository. Does that allow multiple versions per day, say if I make multiple commits in one day? I feel like it might make more sense to base it on the commit hash than a date, but if the convention for nightly builds is release date that's fine.

> I think having a derivation inlined in flake.nix makes it less readable. That's also strictly the same for the flake user, unless I'm missing some details, and I'm not a fan of fetching one more tarball when it doesn't change anything.

That seems reasonable to me, though I'm still not entirely sure what flake-compat does, it seems good to have one less dependency if it's not necessary.

**Comment by comp500** [comment]
Could you split the `--cache` flag into a separate PR? Makes it easier to review and track :)

**Comment by Austreelis** [comment]
So I added one more workflow running on each push to update `vendorSha256`. I kept the job updating `flake.lock` running once a day because it always produces a commit (unless there's no commit on nixpkgs unstable, which is pretty unlikely).

About supported systems, I first included all systems supported by go, filtering out systems that nix definitely doesn't support at all. Translating between nix ad go platform names was kind of sketchy though, and nix doesn't actually support that much system all that well (about half of go's platforms are listed in nixpkgs' supported systems, only a handful are actually not mostly broken, all of which are supported by go). So I just included those eventually.

**Comment by comp500** [comment]
Does this just make a commit every day? I don't really like that, feel like it'll spam the git log with basically useless commits. How often does the stuff it uses from nixpkgs actually change? Surely we can just lock a reasonably recent version, and update it when `vendorSha256` needs to be changed anyway?

**Comment by Austreelis** [comment]
> How often does the stuff it uses from nixpkgs actually change

I don't really know, I'd say a few times a month but definitely not every day.

> we can just lock a reasonably recent version, and update it when vendorSha256 needs to be changed anyway?

I'm not sure how to trigger an update iff `vendorSha256` changes through github actions directly, but a small script in the action could do. I'm pushing changes in a sec.

I'll also squash all those `chore: ...` commits.

While I'm thinking about it: A stupid-simple solution would be to only run the workflow updating the flake manually, and/or the least frequently possible (i.e. monthly).

**Comment by Austreelis** [comment]
- I rebased the branch on master and squashed redundant commits.
- I kept the `update-flake` workflow, but it only runs when manually triggered or once a month
- I updated the `nix` workflow to update the flake lock if the `vendorSha256` changes. I'm not sure how robust it is, but I think it's working well enough to just get rid of the `update-flake` workflow (unless you want to keep the possibility of updating it manually from the actions).

**Comment by Infinidoge** [comment]
Honestly, I really don't think that nixpkgs should be updated automatically

Part of the point of using the flake would be that you're using versions of software that you know to be good and working, and having the flake here break due to an upstream nixpkgs change automatically feels wrong.

**Review by comp500 — APPROVED** [review]
Thanks! Sorry it took so long...

**Pull request merged**
