### PR TITLE
Fix Modrinth getLatestVersion

### PR DESCRIPTION
**Pull request by Chikage0o0**
Fix errors caused by Quilt detection and unstandardized version naming

For example
https://modrinth.com/mod/inventory-profiles-next
https://modrinth.com/mod/fallingtree

I would recommend removing that FOR loop though, the modrinth API returns what I think is the best sort. 
The code here is confusing.

### CODE REVIEW

**Comment by comp500** [comment]
I really don't like having to remove any form of semantic version comparison; relying only on dates is possible (and what the Modrinth "latest version from hash" endpoint does) but requires that the author upload every version in the same order as releases. Release date order is often good enough, but might not be correct when the author uploads many versions at once, or backports new features or applies bugfixes to older versions. This seems like a waste when Modrinth provides a version number field that is intended to be machine-readable (and which [Modrinth suggests should be semver](https://docs.modrinth.com/api-spec/#tag/version_model)).

I think the Quilt preference check does need to be tweaked, but the change you've made still won't fix Inventory Profiles Next *for Quilt users* - packwiz will still prefer the 1.6.0 version marked for Fabric and Quilt over the 1.8.0 version marked for Fabric only (which I assume also supports Quilt - but packwiz doesn't know that). This problem is much more easily solvable with semver (or some other semantically comparable version specification) since packwiz would be able to know that it should prefer a newer version marked only for Fabric over an older version marked for both Quilt and Fabric (or only Quilt, such as if a mod *used* to have separate versions for Quilt and Fabric then merged them into one version).

**Comment by Chikage0o0** [comment]
> I think the Quilt preference check does need to be tweaked, but the change you've made still won't fix Inventory Profiles Next for Quilt users

`if slices.Contains(v.Loaders, "quilt") && slices.Contains(pack.GetLoaders(), "quilt") && !slices.Contains(latestValidVersion.Loaders, "quilt")`
This changes I made are only for when using Fabric, and the mod used to provide dual versions of Quilt and Fabric, the latest version check will have an error, which is a bug that must be fixed. 

And for using the Quilt launcher, a small part of the Fabric module is still incompatible, so I think the current solution is still feasible.

Since version numbers are currently not standardized, it makes no sense to use semver. For example, IPN's fabric-1.18.2-1.8.0 and FallingTree's 1.18.2-3.5.4, as well as the most downloaded mc1.18.2-0.4.1 from Sodium. The comparison is actually 1.18.2, which is not informative and can easily lead to errors. Given the current influence of these mod, I think it's too early to use semver unless we can perfectly solve the problem of version number identification.

**Comment by copygirl** [comment]
We can only hope through tools such as packwiz that mod authors will slowly start adopting more sensible versions that can actually be dealt with by said tools. Someone will have to make the effort to address the issue with the mod authors (nicely, of course). Giving in to lack of standerdization like this will only break other cases, and then someone else will just create an issue for that.

**Comment by Chikage0o0** [comment]
> We can only hope through tools such as packwiz that mod authors will slowly start adopting more sensible versions that can actually be dealt with by said tools. Someone will have to make the effort to address the issue with the mod authors (nicely, of course). Giving in to lack of standerdization like this will only break other cases, and then someone else will just create an issue for that.

We may need to provide a -c/--compatible option for the user to choose

**Comment by Chikage0o0** [comment]
Also,We can pre-process the version number, delete the game version number and then keep only the number and. Then send it to semver for processing

**Pull request closed without merging**
