### PR TITLE
Add Nix support

### PR DESCRIPTION
**Pull request by TheOPtimal**
This PR adds support for [Nix](https://nixos.org/), a functional and reproducible package manager/programming language.

### CODE REVIEW

**Comment by comp500** [comment]
I have no idea what these files do... isn't this something that can be maintained externally? I don't have releases set up for any other packaging systems currently.

**Comment by TheOPtimal** [comment]
Essentially, it turns packwiz into a Nix "flake". You can install a flake as a package, temporarily drop into a shell with a flake, or just use the flake as a dependency.

You don't need to set up any kind of packaging - those files are all that is needed.

**Comment by TheOPtimal** [comment]
P.S. squash the commits when merging

**Comment by comp500** [comment]
Sure, but will I have to update the metadata when I change my dependencies? I'm not sure why this can't just be pushed to a repository for Nix users like https://github.com/NixOS/nixpkgs, rather than being another thing I have to maintain in my repository.

**Comment by TheOPtimal** [comment]
My nix flake uses `buildGoModule` which uses go.mod - I doubt you'll ever need to touch nix. But if there's a major breaking change or a system dependency added, just ping me and I'll take care of it.

Also, with the new bundlers feature - Nix can build package for deb and rpm aswell.

**Comment by TheOPtimal** [comment]
Essentially a flake allows me to do the following:

Run the flake directly, without installing it in my user environment
`nix run github:packwiz/packwiz`

Drop into a shell with the package available
`nix shell github:packwiz/packwiz`

Install it in my user environment
`nix profile install github:packwiz/packwiz`

**Comment by TheOPtimal** [comment]
Any update?

**Comment by Noxom1** [comment]
> Any update?

Yo man, this seems the only place you are active anywhere so, wanted to ask for your discord tag. You use to know me but we lost contact, so I'd like to talk :P

**Comment by TheOPtimal** [comment]
> > Any update?
> 
> Yo man, this seems the only place you are active anywhere so, wanted to ask for your discord tag. You use to know me but we lost contact, so I'd like to talk :P Add me here Gluttony#8935

1. who are you
2. why are you interrupting on an unrelated issue
3. i don't use discord anymore

**Comment by srnyx** [comment]
> Any update?

I don't think this will be added.
You should just keep this on your local machine, there's really no demand for it besides from you.

**Comment by Noxom1** [comment]
>     1. who are you
really weird explaining here, is there a way to contact you? I have no bad intentions or anything I was just going through old things of mine and remembered you so thought I might try find and contact you.
>     2. why are you interrupting on an unrelated issue
This is the only place I could find to contact you, couldn't find anyone who knew you or a way to be able to message you, if I could I wouldn't interrupt anything.
>     3. i don't use discord anymore
Ah sad, do you use anything else?

**Comment by comp500** [comment]
I'm happy to merge this, but only once I actually understand what it does. I'll look into Nix at some point; being able to publish `deb`/`rpm` packages with it does sound nice.

**Comment by Austreelis** [comment]
Everything that @TheOPtimal described is now possible, since [this commit in nixpkgs](https://github.com/NixOS/nixpkgs/commit/9687b5e62e9179467a49fbfcc7a6517bcc2649ca) (`nixpkgs` being the main nix package repository, it's basically a pile of build instructions for nix to build and install packages).

> Run the flake directly, without installing it in my user environment

`nix run nixpkgs#packwiz`

> Drop into a shell with the package available

`nix shell nixpkgs#packwiz`

> Install it in my user environment

`nix profile install nixpkgs#packwiz`

**Comment by comp500** [comment]
I've talked to @Infinidoge about this a bit; it might be better to have both the flake and nixpkgs package, where the flake is more useful as a "nightly" download source? Though it does mean I have to maintain the flake as well; a Github Action to test it builds and update the `vendorSha256` hash when necessary would be nice.
He also mentioned that this PR needs to be updated to use `buildGo118Module` and update the `vendorSha256` hash, and it'd be nice to have it install shell completions for you as well. I'd do it myself but I've got other issues to work on and this isn't super high priority; changes here or a superseding PR would be appreciated.

**Comment by Austreelis** [comment]
I'm not very familiar with building go with nix but I think [dream2nix](https://github.com/nix-community/dream2nix) would help making it painless to maintain. It should handle updating `vendorSha256` and `version` itself, and make the amount of nix code in `packwiz` minimal.

I'll try that this week, and will open a new PR if that turns out well.

**Comment by TheOPtimal** [comment]
> I've talked to @Infinidoge about this a bit; it might be better to have both the flake and nixpkgs package, where the flake is more useful as a "nightly" download source? Though it does mean I have to maintain the flake as well; a Github Action to test it builds and update the `vendorSha256` hash when necessary would be nice. He also mentioned that this PR needs to be updated to use `buildGo118Module` and update the `vendorSha256` hash, and it'd be nice to have it install shell completions for you as well. I'd do it myself but I've got other issues to work on and this isn't super high priority; changes here or a superseding PR would be appreciated.

Yes, this is the approach that PolyMC takes. Nixpkgs isn't very up to date for neish packages, so having a direct flake really does help

> I'm not very familiar with building go with nix but I think [dream2nix](https://github.com/nix-community/dream2nix) would help making it painless to maintain. It should handle updating `vendorSha256` and `version` itself, and make the amount of nix code in `packwiz` minimal.
> 
> I'll try that this week, and will open a new PR if that turns out well.
> 
> Edit: Oopsy: Dream2nix's go utilities aren't mature yet, my bad. I'll just try it the naive way then, and add a github workflow to update `version` and `vendorSha256`.

My current flake barely needs any maintenance.

**Comment by comp500** [comment]
Superseded by https://github.com/packwiz/packwiz/pull/130

**Pull request closed without merging**
